config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {registrations: 'registrations'}

  get 'pages/home' => 'high_voltage/pages#show', id: 'home'
  get 'dashboard' => 'dashboard#show'

  resources :groups, shallow: true do
    resources :matches
    resources :fixtures, only: [:show]
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def show
    @groups = current_user.groups
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/show.html.erb
<h3>My Groups</h3>
<p>Here is a list of the Groups you currently belong to:</p>
<ul>
  <% @groups.each do |group| %>
   <li><%= group.name %> - <%= link_to("Details", group_path(group))%> <%= link_to("Stats", group_matches_path(group))%></li>
  <% end %>
</ul>
<%= link_to('Add a new Group', new_group_path) %>
<br/>
<hr/>
<h3>My Stats:</h3>
<p>Matches Played: <%= current_user.total_matches %></p>
<p>Matches Won: <%= current_user.total_matches_won %></p>
<p>Matches Drawn: <%= current_user.total_matches_drawn %></p>
<p>Matches Lost: <%= current_user.total_matches_lost %></p>
<p>Goals Scored: <%= current_user.total_goals_scored %></p>
<p>Goals Conceded: <%= current_user.total_goals_conceded %></p>
<p>Big Wins: <%= current_user.total_goals_scored %></p>
<p>Big Losses: <%= current_user.total_goals_conceded %></p>
<p>Bore Draws: <%= current_user.total_bore_draws %></p>
<p>Clean Sheets: <%= current_user.total_clean_sheets %></p>