config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {registrations: 'registrations'}

  get 'pages/home' => 'high_voltage/pages#show', id: 'home'
  get 'dashboard' => 'dashboard#show'

  resources :groups, shallow: true do
    resources :matches
    resources :fixtures, only: [:show]
  end

end

app/models/group.rb
class Group < ActiveRecord::Base

  belongs_to :user

  default_scope { where(deleted_on: nil) }

  has_many :users, through: :group_users
  has_many :group_users
  has_many :matches, through: :fixtures
  has_many :fixtures


  validates_presence_of :user

  after_save :add_owner_to_group

  def owner
    user
  end

  def add_owner_to_group
    GroupUser.add_user_to_group(user, self)
  end

  def add_member_to_group(new_member)
    GroupUser.add_user_to_group(new_member, self)
    create_fixtures_for(group_users.last)
  end

  def remove_member_from_group(member)
    @group_user = GroupUser.find_by(user: member, group: self)
    @group_user.deleted_on = Date.today
    @group_user.save
    suspend_fixtures_involving(@group_user)
  end

  def create_fixtures_for(group_user)
    group_users.each do |gu|
      unless(gu == group_user)
       new_fixture = self.fixtures.build(group: self)
       new_fixture.save
       add_group_users_to_fixture(group_user, gu, new_fixture)
      end
    end
  end

  def suspend_fixtures_involving(group_user)
    @fixture_group_users = FixtureGroupUser.where(group_user: group_user)
    @fixtures = []
    @fixture_group_users.each do |fgu|
      @fixtures << Fixture.find(fgu.fixture)
    end
    @fixtures.each do |f|
      f.suspended_on = Date.today
      f.save
    end
  end

  def add_group_users_to_fixture(group_user_one, group_user_two, fixture)
    fixture.fixture_group_users.build(group_user: group_user_one).save
    fixture.fixture_group_users.build(group_user: group_user_two).save
  end

  def members_not_including_owner
    group_users.reject{|gu| gu.user == owner || gu.deleted_on.present? }
  end

  def last_session
    matches.last.created_at unless matches.empty?
  end

  def last_session_date
    last_session.strftime("%-d %B %Y") if last_session
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user
    redirect_to dashboard_path if @group.save
  end

  def show
    @group = Group.find(params[:id])
    @owner = @group.owner
    @other_members = @group.members_not_including_owner
  end

  # Adding users needs to be thought out more
  def edit
    @group = Group.find(params[:id])
    @users = User.all
    @users_to_add = []
    @users.each do |user|
      @users_to_add << user unless (user.groups.include?(@group) || user.group_users.select{|gu| gu.group == @group}.present?)
    end
    @users_to_remove = @group.users.reject{ |u| u == current_user }
  end

  def update
    @group = Group.find(params[:id])
    if params[:update_type] == 'add'
      @new_member = User.find(params[:group][:user_id])
      @group.add_member_to_group(@new_member)
      flash[:alert] = "#{@new_member.name} has been added to this group."
    elsif params[:update_type] == 'remove'
      @member_to_remove = User.find(params[:group][:user_id])
      @group.remove_member_from_group(@member_to_remove)
      flash[:alert] = "#{@member_to_remove.name} has been removed from this group."
    else
      flash[:alert] = "Error somewhere!"
    end
    redirect_to group_path(@group)
  end

  def destroy
    @group = Group.find(params[:id])
    @group.group_users.each do |gu|
      @group.remove_member_from_group(gu)
    end
    @group.deleted_on = Date.today     # should I update attribute in model instead?
    redirect_to dashboard_path if @group.save
  end

  private
  def group_params
    params.require(:group).permit(:name, :user)
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<h3>Edit Group Members</h3>
<h4>Adding Users</h4>

<% if @users_to_add.empty? %>
  <p>There are no users to add to your group.</p>
<% else %>
  <%= form_for @group do |f| %>
    <%= collection_select(:group, :user_id, @users_to_add, :id, :email) %>
    <%= hidden_field_tag :update_type, 'add' %>
    <%= f.submit %>
  <% end %>
<% end %>


<h4>Removing Users</h4>
<% if @users_to_remove.empty? %>
  <p>There are no users to remove from your group.</p>
<% else %>
  <%= form_for @group do |f| %>
    <%= collection_select(:group, :user_id, @users_to_remove, :id, :email) %>
    <%= hidden_field_tag :update_type, :remove %>
    <%= f.submit %>
  <% end %>
  <p><em>Note: Once you remove a user from your Group you will not be able to re-add them.</em></p>
<% end %>

app/views/groups/new.html.erb
<%= form_for @group do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/groups/show.html.erb
<h3><%= @group.name %></h3>
<p>Owner: <%= @owner.name %></p>
<p>Members:</p>
<ul>
  <% @other_members.each do |member| %>
    <li><%= member.name %></li>
  <% end %>
</ul>
<p><%= link_to('Go to Group Stats', group_matches_path(@group)) %></p>
<% if @owner == current_user %>
  <%= link_to('Edit Group Members', edit_group_path(@group)) %></p>
  <%= link_to('Delete this group', group_path(@group), data: { confirm: "Are you sure?" }, method: :delete )%>
<% end %>
<br/>
<hr/>
<p><strong>TODO:</strong> Need to be able to remove yourself from a group</p>