config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {registrations: 'registrations'}

  get 'pages/home' => 'high_voltage/pages#show', id: 'home'
  get 'dashboard' => 'dashboard#show'

  resources :groups, shallow: true do
    resources :matches
    resources :fixtures, only: [:show]
  end

end

app/models/match.rb
class Match < ActiveRecord::Base

  belongs_to :group
  belongs_to :fixture

  has_many :fixture_group_users, through: :match_players
  has_many :match_players, dependent: :destroy

  def add_players_and_goals(fixture, goals)
    MatchPlayer.add_to_match(self, fixture.player_one, goals.first)
    MatchPlayer.add_to_match(self, fixture.player_two, goals.last)
  end

  def player_one
    match_players[0]
  end

  def player_two
    match_players[1]
  end

  def score
    "#{player_one_goals} - #{player_two_goals}"
  end

  def goal_difference
    player_one_goals - player_two_goals
  end

  def draw?
    goal_difference == 0
  end

  def bore_draw?
    player_one_goals == 0 && player_two_goals == 0
  end


  def player_one_goals
    player_one.goals
  end

  def player_two_goals
    player_two.goals
  end

  def player_one_big_win?
    goal_difference > 2
  end

  def player_two_big_win?
    goal_difference < -2
  end

  def amount_of_goals
    player_one_goals + player_two_goals
  end

  def player_one_clean_sheet?
    player_two.goals == 0
  end

  def player_two_clean_sheet?
    player_one.goals == 0
  end

  def display_date
    created_at.strftime("%-d %B %Y")
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def new
    @match = Match.new
    @group = Group.find(params[:group_id])
    @fixtures = @group.fixtures.where(suspended_on: nil)
  end

  def create
    @goals = [params[:user_one_goals], params[:user_two_goals]]
    @fixture = Fixture.find(params[:fixture])
    @group = Group.find(params[:group_id])
    @match = Match.new(group: @group, fixture: @fixture)
    if @match.save
      @match.add_players_and_goals(@fixture, @goals)
      redirect_to group_matches_path(@group)
    end
  end

  def index
    @group = Group.find(params[:group_id])
    @matches = @group.matches
    @fixtures = @group.fixtures
    @group_user = current_group_user(@group)
    @last_session_matches = @group.matches.where("matches.created_at >= :start_date AND matches.created_at <= :end_date",
      {start_date: @group.last_session_date, end_date: @group.last_session})
  end

  # private

  # def match_params
  #   params.permit(:group_id, :user_one, :user_two)
  # end

end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/index.html.erb
<p>Number of matches played by this group: <%= @matches.count %></p>
<%= link_to('Add a match', new_group_match_path(@group)) %>
<%= link_to('Group Details', group_path(@group)) %>
<table>
  <thead>
    <th class="fixture">Fixture</th>
    <th>Matches</th>
    <th>Goals For</th>
    <th>Goals Against</th>
    <th>Goals Per Game For</th>
    <th>Goals Per Game Against</th>
    <th>Goals Per Game</th>
    <th>Wins For</th>
    <th>Draws</th>
    <th>Wins Against</th>
    <th>Big Wins For</th>
    <th>Big Wins Against</th>
    <th>Bore Draws</th>
    <th>Clean Sheets For</th>
    <th>Clean Sheets Against</th>
  </thead>
  <tbody>
  <% @fixtures.each do |fixture| %>
    <tr>
      <td><%= link_to("#{fixture.display}", fixture_path(fixture)) %></td>
      <td><%= fixture.matches_count %></td>
      <td><%= fixture.player_one_goals %></td>
      <td><%= fixture.player_two_goals %></td>
      <td><%= fixture.player_one_goals_per_game %></td>
      <td><%= fixture.player_two_goals_per_game %></td>
      <td><%= fixture.goals_per_game %></td>
      <td><%= fixture.player_one_wins %></td>
      <td><%= fixture.draws %></td>
      <td><%= fixture.player_two_wins %></td>
      <td><%= fixture.player_one_big_wins %></td>
      <td><%= fixture.player_two_big_wins %></td>
      <td><%= fixture.bore_draws %></td>
      <td><%= fixture.player_one_clean_sheets %></td>
      <td><%= fixture.player_two_clean_sheets %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<br/>
<hr/>
<div class="my_stats_group">
  <p><strong>My Stats for <%= @group.name %>:</strong></p>
  <p>Matches Played: <%= @group_user.total_matches %></p>
  <p>Matches Won: <%= @group_user.total_matches_won %></p>
  <p>Matches Drawn: <%= @group_user.total_matches_drawn %></p>
  <p>Matches Lost: <%= @group_user.total_matches_lost %></p>
  <p>Goals Scored: <%= @group_user.total_goals_scored %></p>
  <p>Goals Conceded: <%= @group_user.total_goals_conceded %></p>
  <p>Big Wins: <%= @group_user.total_goals_scored %></p>
  <p>Big Losses: <%= @group_user.total_goals_conceded %></p>
  <p>Bore Draws: <%= @group_user.total_bore_draws %></p>
  <p>Clean Sheets: <%= @group_user.total_clean_sheets %></p>
</div>
<div class="today_group_results">
  <p><strong><%= @group.name %> Results from last session (<%= @group.last_session_date %>):</strong></p>
  <% @last_session_matches.each do |match| %>
    <p><%= match.fixture.display %> - <%= match.score %></p>
  <% end %>
</div>

app/views/matches/new.html.erb
<%= form_for @match, url: group_matches_path do |f| %>
  <%= select_tag(:fixture, options_from_collection_for_select(@fixtures, "id", "display")) %>
  <%= select_tag('user_one_goals', options_for_select((0..20))) %>
  <%= select_tag('user_two_goals', options_for_select((0..20))) %>
  <%= f.submit %>
<% end %>
<p><em>Note: The match date will be the date you enter the result.</em></p>